### ISSUE TITLE
Boots to black screen

### ISSUE THREAD

**Issue by Bigfellas** [BillyBlaze/OctoPrint-TouchUI#22]
I thought I would try and use you new easy to follow wiki page. to get the pi display to boot into touch display. Unfortunately the display is booting to a blank screen with a cursor at the top.

I get the system dialogue while booting but then blank. I know the touch ui is working, it is fine on my iphone.  
Any ideas.
Thanks Matt

**Comment by BillyBlaze** [comment]
Hi Matt, 

Thanks for reporting, do you have an error log located @ `/home/pi/.xsession-errors` you can share??

It seems like everything is working untill it tries to open Iceweasel, but maybe it fails to open unclutter. Hopefully the error log has some more info. If you do not have the `.xsession-errors`, there is also an error log located @ `/var/log/Xorg.0.log`

~Paul

**Comment by Bigfellas** [comment]
Hey Paul sorry literally about to get into a plain. I will get back to you in a week

**Comment by BillyBlaze** [comment]
Okay &  Fly safe

**Comment by Bigfellas** [comment]
Here we go....

Xsession: X session started for pi at Thu Jan 21 17:44:43 AEDT 2016
localuser:pi being added to access control list
Obt-Message: Xinerama extension is not present on the server
Openbox-Message: Requested key "F13" does not exist on the display
Openbox-Message: Unable to find a valid menu file "/usr/share/lxde/openbox/menu.xml"
*\* Message: x-terminal-emulator has very limited support, consider choose another terminal

*\* (pcmanfm:2601): WARNING *_: The directory '~/Templates' doesn't exist, ignoring it
*_ Message: x-terminal-emulator has very limited support, consider choose another terminal

*\* (lxpanel:2600): WARNING **: The directory '~/Templates' doesn't exist, ignoring it

(lxpanel:2600): GLib-GObject-WARNING **: Attempt to add property GtkSettings::gtk-can-change-accels after class was initialised

(lxpanel:2600): GLib-GObject-WARNING **: Attempt to add property GtkSettings::gtk-menu-popup-delay after class was initialised

(lxpanel:2600): GLib-GObject-WARNING **: Attempt to add property GtkSettings::gtk-menu-popdown-delay after class was initialised

(lxpanel:2600): GLib-GObject-WARNING **: Attempt to add property GtkSettings::gtk-menu-images after class was initialised

(lxpanel:2600): GLib-GObject-WARNING **: Attempt to add property GtkSettings::gtk-label-select-on-focus after class was initialised

(lxpanel:2600): GLib-GObject-WARNING **: Attempt to add property GtkSettings::gtk-button-images after class was initialised

(lxpanel:2600): Gtk-CRITICAL **: IA__gtk_misc_set_alignment: assertion 'GTK_IS_MISC (misc)' failed

(lxpanel:2600): Gtk-CRITICAL **: IA__gtk_misc_set_alignment: assertion 'GTK_IS_MISC (misc)' failed

(pcmanfm:2601): GLib-GObject-WARNING **: Attempt to add property GtkSettings::gtk-can-change-accels after class was initialised

(pcmanfm:2601): GLib-GObject-WARNING **: Attempt to add property GtkSettings::gtk-menu-popup-delay after class was initialised

(pcmanfm:2601): GLib-GObject-WARNING **: Attempt to add property GtkSettings::gtk-menu-popdown-delay after class was initialised

(pcmanfm:2601): GLib-GObject-WARNING **: Attempt to add property GtkSettings::gtk-label-select-on-focus after class was initialised

(pcmanfm:2601): GLib-GObject-WARNING **: Attempt to add property GtkSettings::gtk-menu-images after class was initialised

*\* (lxpanel:2600): WARNING **: launchbar: desktop entry does not exist

*\* (lxpanel:2600): WARNING **: launchtaskbar: can't init button

*\* (lxpanel:2600): WARNING **: launchbar: desktop entry does not exist

*\* (lxpanel:2600): WARNING **: launchtaskbar: can't init button

*\* Message: Connecting ...
*\* Message: Status changed to down

(lxpanel:2600): Gtk-CRITICAL *_: IA__gtk_dialog_response: assertion 'GTK_IS_DIALOG (dialog)' failed
*_ Message: Status changed to opened
*\* Message: Connected to dhcpcd-6.7.1
*\* Message: Status changed to connected
*\* Message: eth0: CARRIER
*\* Message: eth0: Configured 192.168.1.250/24
ALSA lib control.c:951:(snd_ctl_open_noupdate) Invalid CTL Äbe¶:

*\* (lxpanel:2600): WARNING **: volumealsa: Default ALSA device not valid - resetting to internal
numid=3,iface=MIXER,name='PCM Playback Route'
  ; type=INTEGER,access=rw------,values=1,min=0,max=2,step=0
  : values=2

(lxpanel:2600): GLib-GObject-WARNING *_: Attempt to add property GtkSettings::gtk-scrolled-window-placement after class was initialised
*_ Message: Status changed to down

(lxpanel:2600): Gtk-CRITICAL **: IA__gtk_dialog_response: assertion 'GTK_IS_DIALOG (dialog)' failed

*\* (lxpanel:2600): CRITICAL *_: dhcpcd_open: No such file or directory
XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":0"
      after 1829 requests (1826 known processed) with 0 events remaining.
XIO:  fatal IO error 4 (Interrupted system call) on X server ":0"
      after 36 requests (36 known processed) with 0 events remaining.
pcmanfm: Fatal IO error 11 (Resource temporarily unavailable) on X server :0.
Xsession: X session started for pi at Wed Jan 27 15:15:12 AEDT 2016
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  109 (X_ChangeHosts)
  Value in failed request:  0x5
  Serial number of failed request:  6
  Current serial number in output stream:  8
localuser:pi being added to access control list
Obt-Message: XKB extension is not present on the server or too old
Obt-Message: Xinerama extension is not present on the server
Obt-Message: XRandR extension is not present on the server
Xlib:  extension "RANDR" missing on display ":1".
Xlib:  extension "RANDR" missing on display ":1".
Xlib:  extension "RANDR" missing on display ":1".
*_ Message: x-terminal-emulator has very limited support, consider choose another terminal
*\* Message: x-terminal-emulator has very limited support, consider choose another terminal

*\* (pcmanfm:3086): WARNING **: The directory '~/Templates' doesn't exist, ignoring it

*\* (lxpanel:3084): WARNING **: The directory '~/Templates' doesn't exist, ignoring it

(lxpanel:3084): GLib-GObject-WARNING **: Attempt to add property GtkSettings::gtk-can-change-accels after class was initialised

(lxpanel:3084): GLib-GObject-WARNING **: Attempt to add property GtkSettings::gtk-menu-popup-delay after class was initialised

(lxpanel:3084): GLib-GObject-WARNING **: Attempt to add property GtkSettings::gtk-menu-popdown-delay after class was initialised

(lxpanel:3084): GLib-GObject-WARNING **: Attempt to add property GtkSettings::gtk-menu-images after class was initialised

(lxpanel:3084): GLib-GObject-WARNING **: Attempt to add property GtkSettings::gtk-label-select-on-focus after class was initialised

(lxpanel:3084): GLib-GObject-WARNING **: Attempt to add property GtkSettings::gtk-button-images after class was initialised

(lxpanel:3084): Gtk-CRITICAL **: IA__gtk_misc_set_alignment: assertion 'GTK_IS_MISC (misc)' failed

(lxpanel:3084): Gtk-CRITICAL **: IA__gtk_misc_set_alignment: assertion 'GTK_IS_MISC (misc)' failed
Openbox-Message: Requested key "Super_L" does not exist on the display
Openbox-Message: Requested key "F13" does not exist on the display
Openbox-Message: Unable to find a valid menu file "/usr/share/lxde/openbox/menu.xml"

(pcmanfm:3086): GLib-GObject-WARNING **: Attempt to add property GtkSettings::gtk-can-change-accels after class was initialised

(pcmanfm:3086): GLib-GObject-WARNING **: Attempt to add property GtkSettings::gtk-menu-popup-delay after class was initialised

(pcmanfm:3086): GLib-GObject-WARNING **: Attempt to add property GtkSettings::gtk-menu-popdown-delay after class was initialised

(pcmanfm:3086): GLib-GObject-WARNING **: Attempt to add property GtkSettings::gtk-label-select-on-focus after class was initialised

(pcmanfm:3086): GLib-GObject-WARNING **: Attempt to add property GtkSettings::gtk-menu-images after class was initialised

*\* (lxpanel:3084): WARNING **: launchbar: desktop entry does not exist

*\* (lxpanel:3084): WARNING **: launchtaskbar: can't init button

*\* (lxpanel:3084): WARNING **: launchbar: desktop entry does not exist

*\* (lxpanel:3084): WARNING **: launchtaskbar: can't init button

*\* Message: Connecting ...
*\* Message: Status changed to down

(lxpanel:3084): Gtk-CRITICAL *_: IA__gtk_dialog_response: assertion 'GTK_IS_DIALOG (dialog)' failed
*_ Message: Status changed to opened
*\* Message: Connected to dhcpcd-6.7.1
*\* Message: Status changed to connected
*\* Message: eth0: CARRIER
*\* Message: eth0: Configured 192.168.1.250/24

(lxpanel:3084): GLib-GObject-WARNING *_: Attempt to add property GtkSettings::gtk-scrolled-window-placement after class was initialised
*_ Message: Status changed to down

(lxpanel:3084): Gtk-CRITICAL **: IA__gtk_dialog_response: assertion 'GTK_IS_DIALOG (dialog)' failed

*\* (lxpanel:3084): CRITICAL *_: dhcpcd_open: No such file or directory
XIO:  fatal IO error 4 (Interrupted system call) on X server ":1"
      after 33 requests (33 known processed) with 0 events remaining.
XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":1"
      after 1839 requests (1839 known processed) with 0 events remaining.
pcmanfm: Fatal IO error 11 (Resource temporarily unavailable) on X server :1.
Xsession: X session started for pi at Wed Jan 27 15:25:47 AEDT 2016
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  109 (X_ChangeHosts)
  Value in failed request:  0x5
  Serial number of failed request:  6
  Current serial number in output stream:  8
localuser:pi being added to access control list
Obt-Message: XKB extension is not present on the server or too old
Obt-Message: Xinerama extension is not present on the server
Obt-Message: XRandR extension is not present on the server
Xlib:  extension "RANDR" missing on display ":1".
Xlib:  extension "RANDR" missing on display ":1".
Xlib:  extension "RANDR" missing on display ":1".
Openbox-Message: Requested key "Super_L" does not exist on the display
Openbox-Message: Requested key "F13" does not exist on the display
Openbox-Message: Unable to find a valid menu file "/usr/share/lxde/openbox/menu.xml"
*_ Message: x-terminal-emulator has very limited support, consider choose another terminal

*\* (pcmanfm:2677): WARNING *_: The directory '~/Templates' doesn't exist, ignoring it
*_ Message: x-terminal-emulator has very limited support, consider choose another terminal

*\* (lxpanel:2675): WARNING **: The directory '~/Templates' doesn't exist, ignoring it

(lxpanel:2675): GLib-GObject-WARNING **: Attempt to add property GtkSettings::gtk-can-change-accels after class was initialised

(lxpanel:2675): GLib-GObject-WARNING **: Attempt to add property GtkSettings::gtk-menu-popup-delay after class was initialised

(lxpanel:2675): GLib-GObject-WARNING **: Attempt to add property GtkSettings::gtk-menu-popdown-delay after class was initialised

(lxpanel:2675): GLib-GObject-WARNING **: Attempt to add property GtkSettings::gtk-menu-images after class was initialised

(lxpanel:2675): GLib-GObject-WARNING **: Attempt to add property GtkSettings::gtk-label-select-on-focus after class was initialised

(lxpanel:2675): GLib-GObject-WARNING **: Attempt to add property GtkSettings::gtk-button-images after class was initialised

(lxpanel:2675): Gtk-CRITICAL **: IA__gtk_misc_set_alignment: assertion 'GTK_IS_MISC (misc)' failed

(lxpanel:2675): Gtk-CRITICAL **: IA__gtk_misc_set_alignment: assertion 'GTK_IS_MISC (misc)' failed

(pcmanfm:2677): GLib-GObject-WARNING **: Attempt to add property GtkSettings::gtk-can-change-accels after class was initialised

(pcmanfm:2677): GLib-GObject-WARNING **: Attempt to add property GtkSettings::gtk-menu-popup-delay after class was initialised

(pcmanfm:2677): GLib-GObject-WARNING **: Attempt to add property GtkSettings::gtk-menu-popdown-delay after class was initialised

(pcmanfm:2677): GLib-GObject-WARNING **: Attempt to add property GtkSettings::gtk-label-select-on-focus after class was initialised

(pcmanfm:2677): GLib-GObject-WARNING **: Attempt to add property GtkSettings::gtk-menu-images after class was initialised

*\* (lxpanel:2675): WARNING **: launchbar: desktop entry does not exist

*\* (lxpanel:2675): WARNING **: launchtaskbar: can't init button

*\* (lxpanel:2675): WARNING **: launchbar: desktop entry does not exist

*\* (lxpanel:2675): WARNING **: launchtaskbar: can't init button

*\* Message: Connecting ...
*\* Message: Status changed to down

(lxpanel:2675): Gtk-CRITICAL *_: IA__gtk_dialog_response: assertion 'GTK_IS_DIALOG (dialog)' failed
*_ Message: Status changed to opened
*\* Message: Connected to dhcpcd-6.7.1
*\* Message: Status changed to connected
*\* Message: eth0: CARRIER
*\* Message: eth0: Configured 192.168.1.250/24

(lxpanel:2675): GLib-GObject-WARNING **: Attempt to add property GtkSettings::gtk-scrolled-window-placement after class was initialised
Xlib:  extension "RANDR" missing on display ":1.0".

(pcmanfm:2677): GLib-GObject-WARNING **: Attempt to add property GtkSettings::gtk-menu-bar-popup-delay after class was initialised

(pcmanfm:2677): GLib-GObject-WARNING **: Attempt to add property GtkSettings::gtk-button-images after class was initialised

(pcmanfm:2677): GLib-GObject-WARNING **: Attempt to add property GtkSettings::gtk-entry-select-on-focus after class was initialised

(pcmanfm:2677): GLib-GObject-WARNING **: Attempt to add property GtkSettings::gtk-entry-password-hint-timeout after class was initialised

(pcmanfm:2677): GLib-GObject-WARNING **: Attempt to add property GtkSettings::gtk-scrolled-window-placement after class was initialised

(lxpanel:2675): Gtk-CRITICAL **: IA__gtk_misc_set_alignment: assertion 'GTK_IS_MISC (misc)' failed

(pcmanfm:2677): Gtk-WARNING **: Radio group does not contain an action with value '0'

(pcmanfm:2677): Gtk-WARNING **: Radio group does not contain an action with value '0'

(lxpanel:2675): Gtk-CRITICAL **: IA__gtk_misc_set_alignment: assertion 'GTK_IS_MISC (misc)' failed

(pcmanfm:2677): GLib-CRITICAL **: Source ID 865 was not found when attempting to remove it
Xlib:  extension "RANDR" missing on display ":1.0".

(leafpad:2746): GLib-GObject-WARNING **: Attempt to add property GtkSettings::gtk-menu-bar-popup-delay after class was initialised

(leafpad:2746): GLib-GObject-WARNING **: Attempt to add property GtkSettings::gtk-label-select-on-focus after class was initialised

(leafpad:2746): GLib-GObject-WARNING **: Attempt to add property GtkSettings::gtk-can-change-accels after class was initialised

(leafpad:2746): GLib-GObject-WARNING **: Attempt to add property GtkSettings::gtk-menu-popup-delay after class was initialised

(leafpad:2746): GLib-GObject-WARNING **: Attempt to add property GtkSettings::gtk-menu-popdown-delay after class was initialised

(leafpad:2746): GLib-GObject-WARNING **: Attempt to add property GtkSettings::gtk-menu-images after class was initialised

(leafpad:2746): GLib-GObject-WARNING **: Attempt to add property GtkSettings::gtk-scrolled-window-placement after class was initialised

(lxpanel:2675): Gtk-CRITICAL **: IA__gtk_misc_set_alignment: assertion 'GTK_IS_MISC (misc)' failed

(leafpad:2746): GLib-GObject-WARNING **: Attempt to add property GtkSettings::gtk-button-images after class was initialised

(leafpad:2746): GLib-GObject-WARNING **: Attempt to add property GtkSettings::gtk-entry-select-on-focus after class was initialised

(leafpad:2746): GLib-GObject-WARNING **: Attempt to add property GtkSettings::gtk-entry-password-hint-timeout after class was initialised

(lxpanel:2675): Gtk-CRITICAL *_: IA__gtk_misc_set_alignment: assertion 'GTK_IS_MISC (misc)' failed
*_ Message: Status changed to down

(lxpanel:2675): Gtk-CRITICAL **: IA__gtk_dialog_response: assertion 'GTK_IS_DIALOG (dialog)' failed

*\* (lxpanel:2675): CRITICAL **: dhcpcd_open: No such file or directory
XIO:  fatal IO error 4 (Interrupted system call) on X server ":1"
      after 33 requests (33 known processed) with 0 events remaining.
XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":1"
      after 7907 requests (7907 known processed) with 0 events remaining.
pcmanfm: Fatal IO error 11 (Resource temporarily unavailable) on X server :1.

**Comment by BillyBlaze** [comment]
Ahh sorry, this is not the log I have been looking for...

Could you run this commands and copy the output?
1. `sudo service touchui stop`
2 `xinit /home/pi/OctoPrint-TouchUI-autostart/start_iceweasel.xinit`

**Comment by Bigfellas** [comment]
Try this one

pi@octopi ~ $ sudo service touchui stop
[ ok ] Stopping TouchUI Daemon: TouchUI.
pi@octopi ~ $ xinit /home/pi/OctoPrint-TouchUI-autostart/start_iceweasel.xinit

_XSERVTransSocketOpenCOTSServer: Unable to open socket for inet6
_XSERVTransOpen: transport open failed for inet6/octopi:0
_XSERVTransMakeAllCOTSServerListeners: failed to open listener for inet6

X.Org X Server 1.12.4
Release Date: 2012-08-27
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.2.0-2-mx5 armv7l Debian
Current Operating System: Linux octopi 4.1.6+ #2 PREEMPT Fri Sep 4 16:36:22 UTC                              2015 armv6l
Kernel command line: dma.dmachans=0x7f35 bcm2708_fb.fbwidth=656 bcm2708_fb.fbhei                             ght=416 bcm2708.boardrev=0x10 bcm2708.serial=0x181f2f08 smsc95xx.macaddr=B8:27:E                             B:1F:2F:08 bcm2708_fb.fbswap=1 bcm2708.disk_led_gpio=47 bcm2708.disk_led_active_                             low=0 sdhci-bcm2708.emmc_clock_freq=250000000 vc_mem.mem_base=0x1ec00000 vc_mem.                             mem_size=0x20000000  dwc_otg.lpm_enable=0 console=ttyAMA0,115200 console=tty1 ro                             ot=/dev/mmcblk0p2 rootfstype=ext4 elevator=deadline rootwait fbcon=map:10 fbcon=                             font:VGA8x8
Build Date: 11 February 2015  09:31:17PM
xorg-server 2:1.12.4-6+deb7u6 (Julien Cristau jcristau@debian.org)
Current version of pixman: 0.33.1
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/var/log/Xorg.0.log", Time: Fri Jan 29 20:08:08 2016
(==) Using config directory: "/etc/X11/xorg.conf.d"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
/home/pi/OctoPrint-TouchUI-autostart/start_iceweasel.xinit: 2: /home/pi/OctoPrin                             : not foundutostart/start_iceweasel.xinit:
/home/pi/OctoPrint-TouchUI-autostart/start_iceweasel.xinit: 3: /home/pi/OctoPrin                             : not foundutostart/start_iceweasel.xinit:
wm_set_cursor_visibility: visible using XCreateFontCursor

(process:2578): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size =                             = 0' failed

(iceweasel:2578): GLib-GObject-WARNING **: Attempt to add property GtkSettings::                             gtk-label-select-on-focus after class was initialised

(iceweasel:2578): GLib-GObject-WARNING **: Attempt to add property GtkSettings::                             gtk-can-change-accels after class was initialised

(iceweasel:2578): GLib-GObject-WARNING **: Attempt to add property GtkSettings::                             gtk-menu-popup-delay after class was initialised

(iceweasel:2578): GLib-GObject-WARNING **: Attempt to add property GtkSettings::                             gtk-menu-popdown-delay after class was initialised

(iceweasel:2578): GLib-GObject-WARNING **: Attempt to add property GtkSettings::                             gtk-button-images after class was initialised

(iceweasel:2578): GLib-GObject-WARNING **: Attempt to add property GtkSettings::                             gtk-menu-bar-popup-delay after class was initialised

(iceweasel:2578): GLib-GObject-WARNING **: Attempt to add property GtkSettings::                             gtk-entry-select-on-focus after class was initialised

(iceweasel:2578): GLib-GObject-WARNING **: Attempt to add property GtkSettings::                             gtk-entry-password-hint-timeout after class was initialised

(iceweasel:2578): GLib-GObject-WARNING **: Attempt to add property GtkSettings::gtk-menu-images after class was initialised
console.error:
  [CustomizableUI]
  Custom widget with id loop-button does not return a valid node
console.error:
  [CustomizableUI]
  Custom widget with id loop-button does not return a valid node

pi@octopi ~ $ sudo service touchui stop
[ ok ] Stopping TouchUI Daemon: TouchUI.
pi@octopi ~ $ xinit /home/pi/OctoPrint-TouchUI-autostart/start_iceweasel.xinit

_XSERVTransSocketOpenCOTSServer: Unable to open socket for inet6
_XSERVTransOpen: transport open failed for inet6/octopi:0
_XSERVTransMakeAllCOTSServerListeners: failed to open listener for inet6

X.Org X Server 1.12.4
Release Date: 2012-08-27
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.2.0-2-mx5 armv7l Debian
Current Operating System: Linux octopi 4.1.6+ #2 PREEMPT Fri Sep 4 16:36:22 UTC                              2015 armv6l
Kernel command line: dma.dmachans=0x7f35 bcm2708_fb.fbwidth=656 bcm2708_fb.fbhei                             ght=416 bcm2708.boardrev=0x10 bcm2708.serial=0x181f2f08 smsc95xx.macaddr=B8:27:E                             B:1F:2F:08 bcm2708_fb.fbswap=1 bcm2708.disk_led_gpio=47 bcm2708.disk_led_active_                             low=0 sdhci-bcm2708.emmc_clock_freq=250000000 vc_mem.mem_base=0x1ec00000 vc_mem.                             mem_size=0x20000000  dwc_otg.lpm_enable=0 console=ttyAMA0,115200 console=tty1 ro                             ot=/dev/mmcblk0p2 rootfstype=ext4 elevator=deadline rootwait fbcon=map:10 fbcon=                             font:VGA8x8
Build Date: 11 February 2015  09:31:17PM
xorg-server 2:1.12.4-6+deb7u6 (Julien Cristau jcristau@debian.org)
Current version of pixman: 0.33.1
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/var/log/Xorg.0.log", Time: Fri Jan 29 20:08:08 2016
(==) Using config directory: "/etc/X11/xorg.conf.d"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
/home/pi/OctoPrint-TouchUI-autostart/start_iceweasel.xinit: 2: /home/pi/OctoPrin                             : not foundutostart/start_iceweasel.xinit:
/home/pi/OctoPrint-TouchUI-autostart/start_iceweasel.xinit: 3: /home/pi/OctoPrin                             : not foundutostart/start_iceweasel.xinit:
wm_set_cursor_visibility: visible using XCreateFontCursor

(process:2578): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size =                             = 0' failed

(iceweasel:2578): GLib-GObject-WARNING **: Attempt to add property GtkSettings::                             gtk-label-select-on-focus after class was initialised

(iceweasel:2578): GLib-GObject-WARNING **: Attempt to add property GtkSettings::                             gtk-can-change-accels after class was initialised

(iceweasel:2578): GLib-GObject-WARNING **: Attempt to add property GtkSettings::                             gtk-menu-popup-delay after class was initialised

(iceweasel:2578): GLib-GObject-WARNING **: Attempt to add property GtkSettings::                             gtk-menu-popdown-delay after class was initialised

(iceweasel:2578): GLib-GObject-WARNING **: Attempt to add property GtkSettings::                             gtk-button-images after class was initialised

(iceweasel:2578): GLib-GObject-WARNING **: Attempt to add property GtkSettings::                             gtk-menu-bar-popup-delay after class was initialised

(iceweasel:2578): GLib-GObject-WARNING **: Attempt to add property GtkSettings::                             gtk-entry-select-on-focus after class was initialised

(iceweasel:2578): GLib-GObject-WARNING **: Attempt to add property GtkSettings::                             gtk-entry-password-hint-timeout after class was initialised

(iceweasel:2578): GLib-GObject-WARNING **: Attempt to add property GtkSettings::gtk-menu-images after class was initialised
console.error:
  [CustomizableUI]
  Custom widget with id loop-button does not return a valid node
console.error:
  [CustomizableUI]
  Custom widget with id loop-button does not return a valid node

**Comment by BillyBlaze** [comment]
Thanks for the log, I have compared yours with mine and although it's not clean, they're exactly the same as mine that does start. I also looked with a co-worker at the logs and we couldn't spot anything ordinary. So we need to dig a bit deeper.

Can you share the logs `/var/log/messages` and `/var/log/Xorg.0.log`, perhaps it's wise to put that in a pastebin.

**Comment by Bigfellas** [comment]
Thanks for Looking.

http://pastebin.com/PYqLB8D4
http://pastebin.com/jYB7tKtw

**Comment by BillyBlaze** [comment]
Ahh, maybe I found it, I think you're using a wrong driver in the X.org configuration. And therefor its failing to load X.org. If we run the calibration, then I hope this problem will be fixed.

You can run these steps to calibrate: https://github.com/BillyBlaze/OctoPrint-TouchUI/issues/23#issuecomment-173679830

**Comment by Bigfellas** [comment]
No good.
There wasn't a 99-calibration.conf is that normal. So I just added the text an created it.

**Comment by BillyBlaze** [comment]
Yeah, that can be normal. Did the calibration work? (i.e. could you see the crosshairs?)

**Comment by Bigfellas** [comment]
yeah I could.. But boots up the same now

**Comment by BillyBlaze** [comment]
Ok :+1: I think we figured it out, big thanks to @foosel for pointing it out.

We think your Raspberry is attaching TouchUI to the HDMI display port. (You could verify that but if not just follow below steps, because it also can be attached to the analog port, depending on your RPi1 setup)
1. Run `sudo nano /etc/X11/xorg.conf.d/99-fbdev.conf`
2. Paste the following code:
   
   ```
   Section "Device"  
     Identifier "myfb"
     Driver "fbdev"
     Option "fbdev" "/dev/fb1"
   EndSection
   ```
3. Save & Exit (CTR-O, ENTER, CTR-X)
4. Run  `sudo chmod +x /etc/X11/xorg.conf.d/99-fbdev.conf`
5. Reboot and hopefully it works

**Comment by Bigfellas** [comment]
Getting closer yeah I am getting an error when it opens the browser and my touch is inverted may need to re calibrate. and I think I need to get rid of the menu bar somehow.
![20160203_081310282_ios](https://cloud.githubusercontent.com/assets/7148505/12776806/fc26678a-caac-11e5-98f5-8544e13b1ba2.jpg)
![20160203_081404647_ios](https://cloud.githubusercontent.com/assets/7148505/12776813/05d530cc-caad-11e5-9e29-a5f1b33f65ec.jpg)

**Comment by foosel** [comment]
The "unresponsive script" stuff can definitely be fixed by upping the value for `dom.max_script_run_time` in `about:config`. Alternatively, do the following in a shell

```
echo 'user_pref("dom.max_script_run_time", 20);' >> ~pi/.mozilla/firefox/*.default/prefs.js
```

Might be that you have to stop the x server with the running iceweasel browser first.

The easiest way to get rid of the UI and put the browser in a real kiosk mode would probably be to install something like a FF Fullscreen or a similar fullscreen extension.

**Comment by BillyBlaze** [comment]
Awesome command Gina :) 

Be sure you stopped iceweael browser first (run `sudo service touchui stop`) else iceweasel will overwrite your addition.

Alternatively for installing the fullscreen extension goto TouchUI > Enable Fullscreen, you can also enable fullscreen mode of firefox in their menu. Once you're in fullscreen mode, iceweasel restores fullscreen mode after turning the Pi on and off again.

**Comment by BillyBlaze** [comment]
As for the inverted axis, follow this:
1. Edit the calibration file you made `sudo nano /etc/X11/xorg.conf.d/99-calibration.conf`
2. Add the following line before the `EndSection` that you copied from the calibration:
   
   ```
   Option "InvertX" "true"
   ```

**Comment by Bigfellas** [comment]
Awesome thanks so much. I will give it a go tomorrow night.

**Comment by Bigfellas** [comment]
Hey Working now. I am still getting the script error at the start. It is really sluggish and a little hard to use on such a small screen. I think it would be cool on the new pi screen.
Thanks For your help

**Comment by BillyBlaze** [comment]
When you get the script error, check the box: "Don't show again" and click the most left button. This should execute all the javascript (now it's partially loaded). Also if you're in fullscreen mode it should be easier to work with the interface.

Also there is a fix in OctoPrint 1.2.9+ that will improve the terminal.

Also in my following release I will address some of the touchscreen 'lag' and try to make it better. (I am also awaiting a browser that supports Hardware Acceleration for better performance)
