### ISSUE TITLE
TouchUI with Octoprint 1.3.10

### ISSUE THREAD

**Issue by tkardaridis** [BillyBlaze/OctoPrint-TouchUI#266]
Hi,
I just upgrade octoprint on 1.3.10 version and since then touchui is not loading. I am getting a red color letters on the screen which says that 
"Octoprint loaded without touchui. Tap to retry."
I am tapping but nothing happens and still getting the same message.

**Comment by BillyBlaze** [comment]
Hi,

The new ForceLogin plugin is the cause of this issue and you can resolve this with the following steps:

1. [Update your bootloader](https://github.com/BillyBlaze/OctoPrint-TouchUI/wiki/Setup:-Update-your-bootloader)
1. Run `sudo ~/TouchUI-autostart/helpers/install`
1. The installer will ask you to configure 'autoLoginAs', set this up as this would auto login for you on localhost

**Comment by tkardaridis** [comment]
Hi,
Thanks for the reply. I have done that but in the autologin configuration asked me only for username and then restart the touchui. So the touchui still asks for credentials. How can i reconfigure autologin?

**Comment by tkardaridis** [comment]
And which credentials should i use? the same as i login in web environment?

**Comment by BillyBlaze** [comment]
You only need to specify an username, did you restart OctoPrint? (autoLoginAs is an OctoPrint feature) Did the installer ask you to restart OctoPrint?

**Comment by tkardaridis** [comment]
Yes but know i am getting a login screen asking for username and password. The username i enter was the username that i am using to login in the web interface from the browser.

**Comment by BillyBlaze** [comment]
That sounds right, can you share the contents of your octoprint log file?

**Comment by tkardaridis** [comment]
Following is the log of the latest startup. From my pc from the browser i can login. In the touchscreen i am getting login screen waiting for credentials.

```
2018-12-15 17:27:16,871 - octoprint.startup - INFO - ******************************************************************************
2018-12-15 17:27:16,873 - octoprint.startup - INFO - Starting OctoPrint 1.3.10
2018-12-15 17:27:16,875 - octoprint.startup - INFO - ******************************************************************************
2018-12-15 17:27:16,942 - octoprint.startup - INFO - We don't appear to be online, not fetching plugin blacklist
2018-12-15 17:27:17,011 - octoprint.plugin.core - INFO - Loading plugins from /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins, /home/pi/.octoprint/plugins and installed plugin packages...
2018-12-15 17:27:19,573 - octoprint.plugin.core - INFO - Found 16 plugin(s) providing 16 mixin implementations, 19 hook handlers
2018-12-15 17:27:19,694 - octoprint.server.heartbeat - INFO - Starting server heartbeat, 900.0s interval
2018-12-15 17:27:19,744 - octoprint.server - INFO - Intermediary server started
2018-12-15 17:27:19,744 - octoprint.plugin.core - INFO - Loading plugins from /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins, /home/pi/.octoprint/plugins and installed plugin packages...
2018-12-15 17:27:20,359 - octoprint.plugin.core - INFO - Found 16 plugin(s) providing 16 mixin implementations, 19 hook handlers
2018-12-15 17:27:20,396 - octoprint.filemanager.storage - INFO - Initializing the file metadata for /home/pi/.octoprint/uploads...
2018-12-15 17:27:20,957 - octoprint.filemanager.storage - INFO - ... file metadata for /home/pi/.octoprint/uploads initialized successfully.
2018-12-15 17:27:20,995 - octoprint.plugins.tracking - INFO - Initialized anonymous tracking
2018-12-15 17:27:21,386 - octoprint.plugins.softwareupdate - INFO - Loaded version cache from disk
2018-12-15 17:27:24,436 - octoprint.util.pip - INFO - Using "/home/pi/oprint/bin/python2 -m pip" as command to invoke pip
2018-12-15 17:27:26,303 - octoprint.util.pip - INFO - Version of pip is 9.0.3
2018-12-15 17:27:26,305 - octoprint.util.pip - INFO - pip installs to /home/pi/oprint/lib/python2.7/site-packages (writable -> yes), --user flag needed -> no, virtual env -> yes
2018-12-15 17:27:26,305 - octoprint.util.pip - INFO - ==> pip ok -> yes
2018-12-15 17:27:26,310 - octoprint.plugin.core - INFO - Initialized 16 plugin implementation(s)
2018-12-15 17:27:26,326 - octoprint.plugin.core - INFO - 16 plugin(s) registered with the system:
|  Action Command Prompt Support (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/action_command_prompt
|  Announcement Plugin (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/announcements
|  Anonymous Usage Tracking (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/tracking
|  Application Keys Plugin (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/appkeys
|  Backup & Restore (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/backup
|  Core Wizard (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/corewizard
|  CuraEngine (<= 15.04) (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/cura
|  Discovery (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/discovery
|  Force Login (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/forcelogin
|  Logging (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/logging
|  Pi Support Plugin (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/pi_support
|  Plugin Manager (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/pluginmanager
|  Printer Safety Check (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/printer_safety_check
|  Software Update (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/softwareupdate
|  TouchUI (0.3.12) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_touchui
|  Virtual Printer (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/virtual_printer
2018-12-15 17:27:26,344 - octoprint.environment - INFO - Detected environment is Python 2.7.13 under Linux (linux2). Details:
|  hardware:
|    cores: 4
|    freq: 1400.0
|    ram: 918192128
|  os:
|    id: linux
|    platform: linux2
|  plugins:
|    pi_support:
|      model: Raspberry Pi 3 Model B Plus Rev 1.3
|      octopi_version: 0.15.1
|  python:
|    pip: 9.0.3
|    version: 2.7.13
|    virtualenv: /home/pi/oprint
2018-12-15 17:27:26,355 - octoprint.server - INFO - Reset webasset folder /home/pi/.octoprint/generated/webassets...
2018-12-15 17:27:26,372 - octoprint.server - INFO - Reset webasset folder /home/pi/.octoprint/generated/.webassets-cache...
2018-12-15 17:27:26,804 - octoprint.server - INFO - Shutting down intermediary server...
2018-12-15 17:27:26,806 - octoprint.server - INFO - Intermediary server shut down
2018-12-15 17:27:26,808 - octoprint.events - INFO - Processing startup event, this is our first event
2018-12-15 17:27:26,809 - octoprint.events - INFO - Adding 0 events to queue that were held back before startup event
2018-12-15 17:27:26,811 - octoprint.filemanager - INFO - Adding backlog items from all storage types to analysis queue...
2018-12-15 17:27:26,815 - octoprint.filemanager - INFO - Added 0 items from storage type "local" to analysis queue
2018-12-15 17:27:26,877 - octoprint.plugins.discovery - INFO - Registered 'OctoPrint instance on octopi' for _http._tcp
2018-12-15 17:27:26,889 - octoprint.plugins.discovery - INFO - Registered 'OctoPrint instance on octopi' for _octoprint._tcp
2018-12-15 17:27:26,900 - octoprint.plugins.discovery - INFO - Registered OctoPrint instance on octopi for SSDP
2018-12-15 17:27:26,921 - octoprint.server - INFO - Listening on http://127.0.0.1:5000
2018-12-15 17:27:26,956 - octoprint.plugins.pluginmanager - INFO - Loaded plugin repository data from disk, was still valid
2018-12-15 17:27:27,392 - octoprint.plugins.pluginmanager - INFO - Loaded notice data from disk, was still valid
2018-12-15 17:27:29,062 - octoprint.util.pip - INFO - Using "/home/pi/oprint/bin/python2 -m pip" as command to invoke pip
2018-12-15 17:27:29,063 - octoprint.util.pip - INFO - pip installs to /home/pi/oprint/lib/python2.7/site-packages (writable -> yes), --user flag needed -> no, virtual env -> yes
2018-12-15 17:27:29,064 - octoprint.util.pip - INFO - ==> pip ok -> yes
2018-12-15 17:27:29,138 - octoprint.util.connectivity_checker - INFO - Connectivity changed from offline to online
2018-12-15 17:27:29,161 - octoprint.plugins.pluginmanager - INFO - Loaded plugin repository data from disk, was still valid
2018-12-15 17:27:29,685 - octoprint.plugins.pluginmanager - INFO - Loaded notice data from disk, was still valid
2018-12-15 17:27:29,934 - octoprint.server.preemptive_cache - INFO - Preemptively caching / (ui _default) for {'query_string': 'l10n=en', 'path': '/', 'base_url': 'http://10.10.0.251/'}
2018-12-15 17:27:30,390 - octoprint.plugins.tracking - INFO - Sent tracking event startup, payload: {'python': '2.7.13', 'ram': 918192128, 'octopi_version': '0.15.1', 'version': u'1.3.10', 'pip': '9.0.3', 'cores': 4, 'freq': 1400.0, 'pi_model': 'Raspberry Pi 3 Model B Plus Rev 1.3', 'os': 'linux'}
2018-12-15 17:27:35,584 - octoprint.server.util.sockjs - INFO - New connection from client: ::1
2018-12-15 17:27:41,920 - octoprint.server.preemptive_cache - INFO - ... done in 11.99s
2018-12-16 00:57:55,075 - octoprint.server.heartbeat - INFO - Server heartbeat <3
2018-12-16 00:57:55,651 - octoprint.plugins.tracking - INFO - Sent tracking event ping, payload: {}
2018-12-16 00:57:59,459 - octoprint.server.util.flask - INFO - Passively logging in user thomaska from ::ffff:10.10.0.198
2018-12-16 00:58:00,099 - octoprint.server.util.sockjs - INFO - New connection from client: ::ffff:10.10.0.198
2018-12-16 00:58:00,169 - octoprint.server.util.flask - INFO - Passively logging in user thomaska from ::ffff:10.10.0.198
2018-12-16 00:58:01,770 - octoprint.plugins.announcements - INFO - Loaded channel _important from https://octoprint.org/feeds/important.xml in 0.49s
2018-12-16 00:58:02,615 - octoprint.plugins.announcements - INFO - Loaded channel _releases from https://octoprint.org/feeds/releases.xml in 0.52s
2018-12-16 00:58:03,262 - octoprint.plugins.announcements - INFO - Loaded channel _blog from https://octoprint.org/feeds/octoblog.xml in 0.57s
2018-12-16 00:58:03,764 - octoprint.plugins.announcements - INFO - Loaded channel _plugins from https://plugins.octoprint.org/feed.xml in 0.43s
2018-12-16 00:58:04,409 - octoprint.plugins.announcements - INFO - Loaded channel _octopi from https://octoprint.org/feeds/octopi.xml in 0.5s
2018-12-16 00:58:07,502 - octoprint.util.pip - INFO - Using "/home/pi/oprint/bin/python2 -m pip" as command to invoke pip
2018-12-16 00:58:07,944 - octoprint.util.pip - INFO - Using "/home/pi/oprint/bin/python2 -m pip" as command to invoke pip
2018-12-16 00:58:12,642 - octoprint.util.pip - INFO - pip installs to /home/pi/oprint/lib/python2.7/site-packages/ (writable -> yes), --user flag needed -> no, virtual env -> yes
2018-12-16 00:58:12,642 - octoprint.util.pip - INFO - ==> pip ok -> yes
2018-12-16 00:58:12,673 - octoprint.plugins.softwareupdate - INFO - Saved version cache to disk
2018-12-16 00:58:12,710 - octoprint.server.util.sockjs - INFO - User thomaska logged in on the socket from client ::ffff:10.10.0.198
2018-12-16 01:08:07,092 - tornado.access - WARNING - 405 POST / (::ffff:10.10.0.141) 8.02ms
2018-12-16 01:08:07,108 - tornado.access - WARNING - 405 POST / (::ffff:10.10.0.141) 7.63ms
2018-12-16 01:08:07,125 - tornado.access - WARNING - 405 POST / (::ffff:10.10.0.141) 7.56ms
2018-12-16 01:12:55,085 - octoprint.server.heartbeat - INFO - Server heartbeat <3
2018-12-16 01:12:55,484 - octoprint.plugins.tracking - INFO - Sent tracking event ping, payload: {}
2018-12-16 01:27:55,093 - octoprint.server.heartbeat - INFO - Server heartbeat <3
2018-12-16 01:27:55,444 - octoprint.plugins.tracking - INFO - Sent tracking event ping, payload: {}
2018-12-16 01:42:55,098 - octoprint.server.heartbeat - INFO - Server heartbeat <3
2018-12-16 01:42:56,184 - octoprint.plugins.tracking - INFO - Sent tracking event ping, payload: {}
2018-12-16 01:57:55,101 - octoprint.server.heartbeat - INFO - Server heartbeat <3
2018-12-16 01:57:55,474 - octoprint.plugins.tracking - INFO - Sent tracking event ping, payload: {}
2018-12-16 02:12:55,108 - octoprint.server.heartbeat - INFO - Server heartbeat <3
2018-12-16 02:12:55,492 - octoprint.plugins.tracking - INFO - Sent tracking event ping, payload: {}
2018-12-16 02:27:55,109 - octoprint.server.heartbeat - INFO - Server heartbeat <3
2018-12-16 02:27:55,472 - octoprint.plugins.tracking - INFO - Sent tracking event ping, payload: {}
2018-12-16 02:42:55,116 - octoprint.server.heartbeat - INFO - Server heartbeat <3
2018-12-16 02:42:55,540 - octoprint.plugins.tracking - INFO - Sent tracking event ping, payload: {}
2018-12-16 02:57:55,117 - octoprint.server.heartbeat - INFO - Server heartbeat <3
2018-12-16 02:57:55,952 - octoprint.plugins.tracking - INFO - Sent tracking event ping, payload: {}
2018-12-16 03:12:55,122 - octoprint.server.heartbeat - INFO - Server heartbeat <3
2018-12-16 03:12:55,823 - octoprint.plugins.tracking - INFO - Sent tracking event ping, payload: {}
2018-12-16 03:27:55,127 - octoprint.server.heartbeat - INFO - Server heartbeat <3
2018-12-16 03:27:56,489 - octoprint.plugins.tracking - INFO - Sent tracking event ping, payload: {}
2018-12-16 03:42:55,137 - octoprint.server.heartbeat - INFO - Server heartbeat <3
2018-12-16 03:42:55,590 - octoprint.plugins.tracking - INFO - Sent tracking event ping, payload: {}
2018-12-16 03:57:55,141 - octoprint.server.heartbeat - INFO - Server heartbeat <3
2018-12-16 03:57:55,511 - octoprint.plugins.tracking - INFO - Sent tracking event ping, payload: {}
2018-12-16 04:12:55,153 - octoprint.server.heartbeat - INFO - Server heartbeat <3
2018-12-16 04:12:55,540 - octoprint.plugins.tracking - INFO - Sent tracking event ping, payload: {}
2018-12-16 04:27:55,157 - octoprint.server.heartbeat - INFO - Server heartbeat <3
2018-12-16 04:27:55,525 - octoprint.plugins.tracking - INFO - Sent tracking event ping, payload: {}
2018-12-16 04:42:55,177 - octoprint.server.heartbeat - INFO - Server heartbeat <3
2018-12-16 04:42:55,739 - octoprint.plugins.tracking - INFO - Sent tracking event ping, payload: {}
2018-12-16 04:57:55,181 - octoprint.server.heartbeat - INFO - Server heartbeat <3
2018-12-16 04:57:55,869 - octoprint.plugins.tracking - INFO - Sent tracking event ping, payload: {}
2018-12-16 05:12:55,186 - octoprint.server.heartbeat - INFO - Server heartbeat <3
2018-12-16 05:12:55,688 - octoprint.plugins.tracking - INFO - Sent tracking event ping, payload: {}
2018-12-16 05:27:55,188 - octoprint.server.heartbeat - INFO - Server heartbeat <3
2018-12-16 05:27:55,811 - octoprint.plugins.tracking - INFO - Sent tracking event ping, payload: {}
2018-12-16 05:42:55,190 - octoprint.server.heartbeat - INFO - Server heartbeat <3
2018-12-16 05:42:55,547 - octoprint.plugins.tracking - INFO - Sent tracking event ping, payload: {}
2018-12-16 05:57:55,201 - octoprint.server.heartbeat - INFO - Server heartbeat <3
2018-12-16 05:57:55,748 - octoprint.plugins.tracking - INFO - Sent tracking event ping, payload: {}
2018-12-16 06:12:55,206 - octoprint.server.heartbeat - INFO - Server heartbeat <3
2018-12-16 06:12:55,556 - octoprint.plugins.tracking - INFO - Sent tracking event ping, payload: {}
2018-12-16 06:27:55,211 - octoprint.server.heartbeat - INFO - Server heartbeat <3
2018-12-16 06:27:55,574 - octoprint.plugins.tracking - INFO - Sent tracking event ping, payload: {}
2018-12-16 06:42:55,224 - octoprint.server.heartbeat - INFO - Server heartbeat <3
2018-12-16 06:42:55,776 - octoprint.plugins.tracking - INFO - Sent tracking event ping, payload: {}
2018-12-16 06:57:55,236 - octoprint.server.heartbeat - INFO - Server heartbeat <3
2018-12-16 06:57:55,765 - octoprint.plugins.tracking - INFO - Sent tracking event ping, payload: {}
2018-12-16 07:12:55,249 - octoprint.server.heartbeat - INFO - Server heartbeat <3
2018-12-16 07:12:55,871 - octoprint.plugins.tracking - INFO - Sent tracking event ping, payload: {}
2018-12-16 07:27:55,254 - octoprint.server.heartbeat - INFO - Server heartbeat <3
2018-12-16 07:27:55,662 - octoprint.plugins.tracking - INFO - Sent tracking event ping, payload: {}
2018-12-16 07:42:55,257 - octoprint.server.heartbeat - INFO - Server heartbeat <3
2018-12-16 07:42:55,732 - octoprint.plugins.tracking - INFO - Sent tracking event ping, payload: {}
2018-12-16 07:57:55,260 - octoprint.server.heartbeat - INFO - Server heartbeat <3
2018-12-16 07:57:55,869 - octoprint.plugins.tracking - INFO - Sent tracking event ping, payload: {}
2018-12-16 08:12:55,263 - octoprint.server.heartbeat - INFO - Server heartbeat <3
2018-12-16 08:12:55,659 - octoprint.plugins.tracking - INFO - Sent tracking event ping, payload: {}
2018-12-16 08:27:55,266 - octoprint.server.heartbeat - INFO - Server heartbeat <3
2018-12-16 08:27:55,661 - octoprint.plugins.tracking - INFO - Sent tracking event ping, payload: {}
2018-12-16 08:42:55,268 - octoprint.server.heartbeat - INFO - Server heartbeat <3
2018-12-16 08:42:55,688 - octoprint.plugins.tracking - INFO - Sent tracking event ping, payload: {}
2018-12-16 08:57:55,270 - octoprint.server.heartbeat - INFO - Server heartbeat <3
2018-12-16 08:57:55,746 - octoprint.plugins.tracking - INFO - Sent tracking event ping, payload: {}
2018-12-16 09:12:55,274 - octoprint.server.heartbeat - INFO - Server heartbeat <3
2018-12-16 09:12:55,670 - octoprint.plugins.tracking - INFO - Sent tracking event ping, payload: {}
2018-12-16 09:27:55,277 - octoprint.server.heartbeat - INFO - Server heartbeat <3
2018-12-16 09:27:55,710 - octoprint.plugins.tracking - INFO - Sent tracking event ping, payload: {}
2018-12-16 09:42:55,279 - octoprint.server.heartbeat - INFO - Server heartbeat <3
2018-12-16 09:42:55,689 - octoprint.plugins.tracking - INFO - Sent tracking event ping, payload: {}
2018-12-16 09:57:55,281 - octoprint.server.heartbeat - INFO - Server heartbeat <3
2018-12-16 09:57:56,002 - octoprint.plugins.tracking - INFO - Sent tracking event ping, payload: {}
2018-12-16 10:12:55,284 - octoprint.server.heartbeat - INFO - Server heartbeat <3
2018-12-16 10:12:55,727 - octoprint.plugins.tracking - INFO - Sent tracking event ping, payload: {}
2018-12-16 10:27:55,287 - octoprint.server.heartbeat - INFO - Server heartbeat <3
2018-12-16 10:27:56,030 - octoprint.plugins.tracking - INFO - Sent tracking event ping, payload: {}
2018-12-16 10:42:55,290 - octoprint.server.heartbeat - INFO - Server heartbeat <3
2018-12-16 10:42:55,989 - octoprint.plugins.tracking - INFO - Sent tracking event ping, payload: {}
2018-12-16 10:57:55,293 - octoprint.server.heartbeat - INFO - Server heartbeat <3
2018-12-16 10:57:55,876 - octoprint.plugins.tracking - INFO - Sent tracking event ping, payload: {}
2018-12-16 11:12:55,296 - octoprint.server.heartbeat - INFO - Server heartbeat <3
2018-12-16 11:12:55,742 - octoprint.plugins.tracking - INFO - Sent tracking event ping, payload: {}
```

**Comment by BillyBlaze** [comment]
ahhh I think I get it, autoLoginAs only works by default with IPv4, and we are connecting with IPv6

can you add the following to your `config.yaml` right under `accessControl:`
```
  localNetworks:
  - 127.0.0.0/8
  - ::1
```

After editing the config, restart octoprint to see if it works

**Comment by tkardaridis** [comment]
are the - required or not? I added both with and without but still the touchscreen requires login credentials. From the web interface it works and i can login. 
Unfortunately no it does not work.

**Comment by BillyBlaze** [comment]
yes, the two white-space characters and the hyphen are required

**Comment by BillyBlaze** [comment]
@foosel 
can you help us with the right config to autoLoginAs with an IPv6 connection?
also can we add IPv6 localhost as default connection for autoLoginAs too?

**Comment by tkardaridis** [comment]
I just add the followings:
localNetworks:
  - 127.0.0.0/8
  - ::1
  - 10.10.0.0/24

10.x.x.x is my local network. I restart the Octoprint and also the touchui service but still nothing.
The touch screen in raspberry is waiting for credentials.

**Comment by onur-elbirlik** [comment]
I still get Failed message with sudo ~/TouchUI-autostart/helpers/install command.

I did all instructions from other sources as well,
changed 
  Option "fbdev" "/dev/fb1" to fb0 etc.
nothing works. my touch ui doesnt work on my touchscreen. i only see octopi login: terminal on touchscreen. problem is same both on 1.3.8 and 1.3.10

**Comment by BillyBlaze** [comment]
@onur-elbirlik please create your own issue, since it's not related.

**Comment by foosel** [comment]
> @foosel
> can you help us with the right config to autoLoginAs with an IPv6 connection?

You mean `localNetworks`, not `autoLoginAs`, right? Because the latter is the name of the user to login as and has nothing to do with v6 or not.

This works for me:

``` yaml
accessControl:
  autoLoginAs: myUser
  autologinLocal: true
  localNetworks:
    - "127.0.0.1/8"
    - "::1/128"
```

(Note the CIDR network notation - we want networks here, not addresses)

> also can we add IPv6 localhost as default connection for autoLoginAs too?

Yep, will do so right away.

**Comment by BillyBlaze** [comment]
Awesome, thanks for the help! and for of adding IPv6 support! 👍 

@tkardaridis 
can you try the config as posted by @foosel

**Comment by jimmyeao** [comment]
Im having this issue also, I still get prompted to login on every boot.
Things I have tried so far:
Ticking "remember me" (does nothing)
Updated bootloader
Run sudo ~/TouchUI-autostart/helpers/install (Says user Jimmy is already configured)
Edited the config.yaml:
```
accessControl:
  autologinAs: jimmy
  autologinLocal: true
  salt: somelonghash
  localnetworks:
    - "127.0.0.1/8"
    - "::1/128"
```
Where do I find the logs?

**Comment by BillyBlaze** [comment]
the log is located at `~/.octoprint/logs/octoprint.log`

**Comment by tkardaridis** [comment]
No it does not work unfortunately
I edited config.yaml as follows:

```
 accessControl:
  autologinAs: thomaska
  autologinLocal: true
  salt: somelonghash
  localNetworks:
    - "127.0.0.1/8"
    - "::1/128"
    - "10.10.0.1/24"
```

**Comment by BillyBlaze** [comment]
Please provide your octoprint log.
Also I assume the username is case-sensitive, can you double check too?

**Comment by jimmyeao** [comment]
Checked the case on the uname - all lower case in the config

```2018-12-19 13:07:51,732 - octoprint.startup - INFO - ******************************************************************************
2018-12-19 13:07:51,734 - octoprint.startup - INFO - Starting OctoPrint 1.3.10
2018-12-19 13:07:51,735 - octoprint.startup - INFO - ******************************************************************************
2018-12-19 13:07:51,813 - octoprint.startup - INFO - We don't appear to be online, not fetching plugin blacklist
2018-12-19 13:07:51,881 - octoprint.plugin.core - INFO - Loading plugins from /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins, /home/pi/.octoprint/plugins and installed plugin packages...
2018-12-19 13:07:53,724 - octoprint.plugin.core - INFO - Plugin Force Login is disabled.
2018-12-19 13:07:56,415 - octoprint.plugin.core - INFO - Found 29 plugin(s) providing 28 mixin implementations, 36 hook handlers
2018-12-19 13:07:56,432 - octoprint.server.heartbeat - INFO - Starting server heartbeat, 900.0s interval
2018-12-19 13:07:56,640 - octoprint.server - INFO - Intermediary server started
2018-12-19 13:07:56,640 - octoprint.plugin.core - INFO - Loading plugins from /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins, /home/pi/.octoprint/plugins and installed plugin packages...
2018-12-19 13:07:57,376 - octoprint.plugin.core - INFO - Found 29 plugin(s) providing 28 mixin implementations, 36 hook handlers
2018-12-19 13:07:57,415 - octoprint.filemanager.storage - INFO - Initializing the file metadata for /home/pi/.octoprint/uploads...
2018-12-19 13:07:57,420 - octoprint.filemanager.storage - INFO - ... file metadata for /home/pi/.octoprint/uploads initialized successfully.
2018-12-19 13:07:57,779 - octoprint.plugins.softwareupdate - INFO - Loaded version cache from disk
2018-12-19 13:08:01,647 - octoprint.util.pip - INFO - Using "/home/pi/oprint/bin/python2 -m pip" as command to invoke pip
2018-12-19 13:08:03,862 - octoprint.util.pip - INFO - Version of pip is 9.0.3
2018-12-19 13:08:03,864 - octoprint.util.pip - INFO - pip installs to /home/pi/oprint/lib/python2.7/site-packages (writable -> yes), --user flag needed -> no, virtual env -> yes
2018-12-19 13:08:03,866 - octoprint.util.pip - INFO - ==> pip ok -> yes
2018-12-19 13:08:04,108 - octoprint.plugin.core - INFO - Initialized 28 plugin implementation(s)
2018-12-19 13:08:04,123 - py.warnings - WARNING - /home/pi/oprint/local/lib/python2.7/site-packages/octoprint/util/__init__.py:623: UnicodeWarning: Unicode unequal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if value_source != value_target:

2018-12-19 13:08:04,146 - octoprint.plugin.core - INFO - 29 plugin(s) registered with the system:
|  Action Command Prompt Support (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/action_command_prompt
|  Announcement Plugin (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/announcements
|  Anonymous Usage Tracking (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/tracking
|  Application Keys Plugin (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/appkeys
|  Backlash autocalibration (0.1) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_autocalibration
|  Backup & Restore (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/backup
|  Bed Visualizer (0.1.7) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_bedlevelvisualizer
|  BLTouch Plugin (0.2.0) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_BLTouch
|  Core Wizard (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/corewizard
|  Cost Estimation (2.1.2) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_costestimation
|  CuraEngine (<= 15.04) (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/cura
|  DeleteAfterPrint Plugin (1.1.1) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_DeleteAfterPrint
|  Detailed Progress Plugin (0.1.4) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_detailedprogress
|  Discovery (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/discovery
|  DisplayProgress (0.1.2) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_displayprogress
|  Filament Manager (0.5.3) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_filamentmanager
| !Force Login (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/forcelogin
|  Fullscreen Plugin (0.0.4) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_fullscreen
|  Logging (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/logging
|  Octolapse (0.3.4) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_octolapse
|  Pi Support Plugin (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/pi_support
|  Plugin Manager (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/pluginmanager
|  Printer Safety Check (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/printer_safety_check
|  Software Update (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/softwareupdate
|  Tab Order (0.5.0) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_taborder
|  Themeify (1.2.0) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_themeify
|  TouchUI (0.3.12) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_touchui
|  TP-Link Smartplug (0.9.10) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_tplinksmartplug
|  Virtual Printer (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/virtual_printer
2018-12-19 13:08:04,165 - octoprint.environment - INFO - Detected environment is Python 2.7.13 under Linux (linux2). Details:
|  hardware:
|    cores: 4
|    freq: 1400.0
|    ram: 972230656
|  os:
|    id: linux
|    platform: linux2
|  plugins:
|    pi_support:
|      model: Raspberry Pi 3 Model B Plus Rev 1.3
|      octopi_version: 0.15.1
|  python:
|    pip: 9.0.3
|    version: 2.7.13
|    virtualenv: /home/pi/oprint
2018-12-19 13:08:04,177 - octoprint.server - INFO - Reset webasset folder /home/pi/.octoprint/generated/webassets...
2018-12-19 13:08:04,204 - octoprint.server - INFO - Reset webasset folder /home/pi/.octoprint/generated/.webassets-cache...
2018-12-19 13:08:04,469 - octoprint.plugins.octolapse - INFO - Octolapse is loading assets.
2018-12-19 13:08:05,199 - octoprint.server - INFO - Shutting down intermediary server...
2018-12-19 13:08:05,654 - octoprint.server - INFO - Intermediary server shut down
2018-12-19 13:08:05,657 - octoprint.events - INFO - Processing startup event, this is our first event
2018-12-19 13:08:05,658 - octoprint.events - INFO - Adding 0 events to queue that were held back before startup event
2018-12-19 13:08:05,661 - octoprint.filemanager - INFO - Adding backlog items from all storage types to analysis queue...
2018-12-19 13:08:05,697 - octoprint.filemanager - INFO - Added 0 items from storage type "local" to analysis queue
2018-12-19 13:08:05,784 - octoprint.util.comm - INFO - Changing monitoring state from "Offline" to "Opening serial port"
2018-12-19 13:08:05,790 - octoprint.util.comm - INFO - Changing monitoring state from "Opening serial port" to "Detecting baudrate"
2018-12-19 13:08:05,794 - octoprint.plugins.discovery - INFO - Registered 'OctoPrint instance on octopi' for _http._tcp
2018-12-19 13:08:05,809 - octoprint.plugins.discovery - INFO - Registered 'OctoPrint instance on octopi' for _octoprint._tcp
2018-12-19 13:08:05,816 - octoprint.plugins.discovery - INFO - Registered OctoPrint instance on octopi for SSDP
2018-12-19 13:08:05,920 - octoprint.server - INFO - Listening on http://127.0.0.1:5000
2018-12-19 13:08:05,924 - octoprint.plugins.octolapse - INFO - Loading existing settings file from: /home/pi/.octoprint/data/octolapse/settings.json.
2018-12-19 13:08:06,024 - octoprint.plugins.bedlevelvisualizer - INFO - OctoPrint-BedLevelVisualizer loaded!
2018-12-19 13:08:06,112 - octoprint.plugins.filamentmanager - ERROR - Failed to set temperature offsets: offsets contains invalid values: {'tool0': u''}
2018-12-19 13:08:06,208 - octoprint.plugins.pluginmanager - INFO - Loaded plugin repository data from disk, was still valid
2018-12-19 13:08:06,812 - octoprint.util.comm - INFO - M110 detected, setting current line number to 0
2018-12-19 13:08:06,949 - octoprint.plugins.pluginmanager - INFO - Loaded notice data from disk, was still valid
2018-12-19 13:08:07,165 - octoprint.util.comm - INFO - Changing monitoring state from "Detecting baudrate" to "Operational"
2018-12-19 13:08:07,175 - octoprint.util.comm - INFO - M110 detected, setting current line number to 0
2018-12-19 13:08:08,472 - octoprint.util.pip - INFO - Using "/home/pi/oprint/bin/python2 -m pip" as command to invoke pip
2018-12-19 13:08:08,473 - octoprint.util.pip - INFO - pip installs to /home/pi/oprint/lib/python2.7/site-packages (writable -> yes), --user flag needed -> no, virtual env -> yes
2018-12-19 13:08:08,474 - octoprint.util.pip - INFO - ==> pip ok -> yes
2018-12-19 13:08:08,507 - octoprint.util.connectivity_checker - INFO - Connectivity changed from offline to online
2018-12-19 13:08:08,688 - octoprint.plugins.pluginmanager - INFO - Loaded plugin repository data from disk, was still valid
2018-12-19 13:08:09,133 - octoprint.plugins.pluginmanager - INFO - Loaded notice data from disk, was still valid
2018-12-19 13:08:09,347 - octoprint.plugins.tplinksmartplug - INFO - TPLinkSmartplug loaded!
2018-12-19 13:08:09,429 - octoprint.server.preemptive_cache - INFO - Preemptively caching / (ui _default) for {'query_string': 'l10n=en', 'path': '/', 'base_url': 'http://octopi/'}
2018-12-19 13:08:12,648 - octoprint.util.comm - INFO - Printer reports firmware name "Marlin 1.1.9 (Github)"
2018-12-19 13:08:12,878 - octoprint.util.comm - INFO - Firmware states that it supports temperature autoreporting
2018-12-19 13:08:53,478 - octoprint.server.preemptive_cache - INFO - ... done in 44.05s
2018-12-19 13:08:53,478 - octoprint.server.preemptive_cache - INFO - Preemptively caching / (ui _default) for {'query_string': 'l10n=en', 'path': '/', 'base_url': 'http://[::1]/'}
2018-12-19 13:08:53,673 - octoprint.server.preemptive_cache - INFO - ... done in 0.19s
2018-12-19 13:08:53,674 - octoprint.server.preemptive_cache - INFO - Preemptively caching / (ui _default) for {'query_string': 'l10n=en', 'path': '/', 'base_url': 'http://192.168.0.217/'}
2018-12-19 13:09:01,563 - octoprint.server.util.sockjs - INFO - New connection from client: ::1
2018-12-19 13:09:02,719 - octoprint.server.preemptive_cache - INFO - ... done in 9.04s
2018-12-19 13:09:02,720 - octoprint.server.preemptive_cache - INFO - Preemptively caching / (ui _default) for {'query_string': 'l10n=en', 'path': '/', 'base_url': 'http://octopi.local/'}
2018-12-19 13:09:04,923 - tornado.access - WARNING - 403 POST /api/plugin/DeleteAfterPrint (::1) 2529.72ms
2018-12-19 13:09:10,878 - octoprint.server.preemptive_cache - INFO - ... done in 8.16s
```

**Comment by BillyBlaze** [comment]
just double checking: The username in OctoPrint has also been created in lower case?

**Comment by jimmyeao** [comment]
yes, all lower case

**Comment by BillyBlaze** [comment]
@foosel I am out of ideas, do you have any pointers?

**Comment by foosel** [comment]
It's `localNetworks` with an uppercase `N`, @jimmyeao has `localnetworks` with a lowercase `n`:

``` yaml
accessControl:
  autologinAs: jimmy
  autologinLocal: true
  salt: somelonghash
  localnetworks:
    - "127.0.0.1/8"
    - "::1/128"
```

That should be

``` yaml
accessControl:
  autologinAs: jimmy
  autologinLocal: true
  salt: somelonghash
  localNetworks:
    - "127.0.0.1/8"
    - "::1/128"
```

No idea about @tkardaridis though,  would need logs for that.

**Comment by jimmyeao** [comment]
@foosel Sorted, many thanks!

>  It's localNetworks with an uppercase N, @jimmyeao has localnetworks with a lowercase n:
> 
> accessControl:
>   autologinAs: jimmy
>   autologinLocal: true
>   salt: somelonghash
>   localnetworks:
>     - "127.0.0.1/8"
>     - "::1/128"

**Comment by tkardaridis** [comment]
Attached my octoprint log. i have done an octoprint restart and touchui service restart before atrtaching the file.
[octoprint.log](https://github.com/BillyBlaze/OctoPrint-TouchUI/files/2696050/octoprint.log)

**Comment by BillyBlaze** [comment]
@foosel, thanks!!! I totally overlooked that one 👍 

@tkardaridis, is there a white-space character in-front of 'accessControl:'?

**Comment by tkardaridis** [comment]
no the is no white-space in-front of "accessControl"

**Comment by BillyBlaze** [comment]
@foosel, can you have a second look at @tkardaridis issue, the log is there and the properties in his config looks correct to me.

**Comment by viper-666** [comment]
I have the same issue, autologin don't work. So I added to my config.yaml:
accessControl:
  autologinAs: xxxx
  autologinLocal: true
  salt: somelonghash
  localNetworks:
    - "127.0.0.1/8"
    - "::1/128"

Now autologin seems to work but I see the TouchIU logo and under the logo "Connecting to TouchIU server" but after a while the logo turned red an the connection fails.
When I comment the localNetworks out the Login screen comes back and I after log in TouchIU works.
I don't think that I have IP6 on my network, I reached the Server under 192.168.178.28.

**Comment by foosel** [comment]
@BillyBlaze sorry, I'm all out of ideas. What I pasted above worked here and is also how it's supposed to work 🤷‍♀️

If push comes to shove, disabling the ForceLogin plugin should bring back the prior behaviour.

**Comment by foosel** [comment]
I don't think that this will help here since we are looking at a `::1` client address,, but I still wanted to mention that I had a similar issue reported in foosel/OctoPrint#2976 where the hybrid notation of the v4 address `192.168.0.26` = `::ffff:192.168.0.26` could not be matched against an entry `192.168.0.0/24` in `localNetworks`. The solution here was to also add `::ffff:192.168.0.0/120`. 

I've pushed a commit that will automatically do this for v4 subnets, e.g. also add an entry `::ffff:127.0.0.0/104` for `127.0.0.0/8`. It will be part of 1.3.11.

You could check if adding `::ffff:127.0.0.0/104` to `localNetworks` helps if `::1/128` doesn't do it, but I have my doubts it will make any difference and am still drawing a blank on the issues still observed here.

**Comment by viper-666** [comment]
OK, the change to 
::ffff:127.0.0.0/104 
and
  - 127.0.0.0/8
  - 192.168.178.0/24
  - ::1/128
  - ::ffff:192.168.178.0/120
don't work for me.
I also tested if it is an issue with wlan, I added an Lan cable but this dosn't change anything.

Maybe it's a problem with the raspberry 3b+ I have???
I think most of the users have an older raspberry.

**Comment by foosel** [comment]
> Maybe it's a problem with the raspberry 3b+ I have???
> I think most of the users have an older raspberry.

I wouldn't say that:

![image](https://user-images.githubusercontent.com/83657/51171722-e7dfe980-18b1-11e9-8646-0162f6bb0ffb.png)

**Comment by danconsole** [comment]
[octoprint (1).log](https://github.com/BillyBlaze/OctoPrint-TouchUI/files/2872468/octoprint.1.log)

I think I'm having the same issue. Tried foosel's suggestions, no idea what else to do except the old USB keyboard. Any new ideas? 

(sorry for the huge log btw)

**Comment by tkardaridis** [comment]
Just to mention that the issue remains. I haven't resolve it. The autologin is not working.

**Comment by viper-666** [comment]
I haven't been able to solve the problem either. In order to get further I deactivated the password request. It's not the best solution but always using a USB keyboard on the printer was not possible.

**Comment by mkh595** [comment]
I had same issue on HDMI display with "Octoprint loaded without touchui. Tap to retry.". 
I did what you propose at begining:
_1. Update your bootloader
2. Run sudo ~/TouchUI-autostart/helpers/install
3. The installer will ask you to configure 'autoLoginAs', set this up as this would auto login for you on localhost_

After this Octoprint changed to Touch UI also in web browser on laptot and I cannot deactivate it. So I cannot use OctoPrint via web anymore.

![TouchUI](https://user-images.githubusercontent.com/30566575/63130350-6886d580-bfba-11e9-884c-cc99d758be7d.PNG)

Many thanks for such piece of junk.

**Comment by JBSullivan** [comment]
I haven't used Octoprint in a long time. Today I started my Octopi installation incl. TouchUI and I was offered a lot of updates.

As a good user I have executed all updates and now I have the salad. I get exactly the same error as all the others displayed here.

OK, I thought to myself - first do a bootloader update.

cd ~/TouchUI-autostart/
git pull

But already here comes the first error message, which has the consequence that the command "sudo ~/TouchUI-autostart/helpers/install" cannot be executed with me and/or is not installed over git pull.

Where is the error?
------------------------------------------------------------------------------------------------------------------------
pi@octopi:~/TouchUI autostart $ git pull
Update 804131b..e8b13cb
error: Your local changes in the following files would be affected by the merge
can be overwritten:
        touchui.default
Please commit or stash your changes before merging.
Cancel

What does committing or stashen mean?
------------------------------------------------------------------------------------------------------------------------
 Here is the content of the file touchui.default

# Configuration for /etc/init.d/touchui

# The init.d script will only run if this variable non-empty.
TOUCHUI_USER=pi

# Where is the xinit file locatated
TOUCHUI_DIR="TouchUI autostart"

# And what xinit file are we looking for
TOUCHUI_FILE="chromium.xinit"

# TouchUI server port
TOUCHUI_PORT="8888"

# Path to the xinit executable, use this to override the default setting "/usr/bin/xinit"
#DAEMON=/path/to/xinit/executable

# What arguments to pass to xinit, usually no need to touch this
DAEMON_ARGS=/home/$TOUCHUI_USER/$TOUCHUI_DIR/$TOUCHUI_FILE

# Umask of files touchui generates, Change this to 000 if running touchui as its own, separate user
UMASK=022

# Process priority, 0 here will result in a priority 20 process.
-2 ensures touchui has a slight priority over user processes.
NICELEVEL=-2

# Should we run at startup?
START=yes

# Should Chromium start with touch events? (false or true)
FORCE_TOUCH=false

# Enable or disable the screensaver
DISABLE_SCREENSAVER=true

Anybody got a smart idea about this?

Translated with www.DeepL.com/Translator

**Comment by turbojunke** [comment]
where is the config.yaml file located??

**Comment by jonasuea** [comment]
> onde está localizado o arquivo config.yaml?

Para se ter acesso direto ao TouchiUI sem precisar fazer login, basta editar este arquivo.

sudo nano /home/pi/.octoprint/config.yaml

accessControl:
  autologinAs: **jonasuea** 
  autologinLocal: true
  
Editando apenas o que está em negrito de acordo com o seu usuário cadastrado no octoprint web
